# Generated by Django 5.2.7 on 2025-11-20 21:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('is_completed', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('prediction_deadline', models.DateTimeField(null=True)),
                ('scoring_config', models.JSONField(blank=True, default=dict, help_text='Scoring configuration for the module')),
                ('finalization_delay_minutes', models.IntegerField(default=60, help_text='Minutes after end_date to trigger finalization')),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('blocking_advancement', models.BooleanField(default=True, help_text='If True, this module must complete before stage can advance to next')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CloudflareCookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(default='www.hltv.org', help_text='Domain the cookies are valid for', max_length=255)),
                ('cf_clearance', models.TextField(help_text='The cf_clearance cookie value')),
                ('cf_bm', models.TextField(blank=True, help_text='The __cf_bm cookie value (optional)')),
                ('user_agent', models.TextField(blank=True, help_text='User agent that was used when obtaining cookies')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('use_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Cloudflare Cookie',
                'verbose_name_plural': 'Cloudflare Cookies',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='StatPredictionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier for programmatic lookup', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('prediction_key', models.CharField(help_text='Unique key to link predictions with results', max_length=255)),
                ('url_template', models.CharField(blank=True, help_text='HLTV URL template with {event_id} placeholder. Example: https://www.hltv.org/stats/leaderboards/kills?event={event_id}', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Stat prediction categories',
            },
        ),
        migrations.CreateModel(
            name='StatPredictionScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('rules', models.JSONField(help_text='Scoring configuration using the scoring engine format. Example: {"rules": [{"id": "top_1", "condition": {...}, "scoring": {...}}]}')),
            ],
        ),
        migrations.CreateModel(
            name='SwissScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SwissScoreGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('hltv_url', models.URLField(blank=True, help_text='HLTV tournament page URL (e.g., https://www.hltv.org/events/7148/...)', null=True)),
                ('hltv_event_id', models.IntegerField(blank=True, help_text='HLTV event ID for URL template substitution', null=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('basemodule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fantasy.basemodule')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('fantasy.basemodule',),
        ),
        migrations.CreateModel(
            name='StatPredictionsModule',
            fields=[
                ('basemodule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fantasy.basemodule')),
                ('max_picks_per_player', models.PositiveIntegerField(default=1, help_text='How many times a single player can be picked in this module.')),
                ('max_players_per_team', models.PositiveIntegerField(blank=True, help_text='Maximum number of players that can be picked from a single team.', null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('fantasy.basemodule',),
        ),
        migrations.CreateModel(
            name='SwissModule',
            fields=[
                ('basemodule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fantasy.basemodule')),
            ],
            options={
                'ordering': ['tournament', 'start_date'],
            },
            bases=('fantasy.basemodule',),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('predictionoption_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fantasy.predictionoption')),
                ('hltv_id', models.IntegerField(blank=True, help_text="The team's ID on HLTV.org", null=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('hltv_page', models.URLField(blank=True, null=True)),
                ('aliases', models.JSONField(blank=True, default=list, help_text='List of alternative names for search purposes.')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=('fantasy.predictionoption',),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('is_completed', models.BooleanField(default=False)),
                ('hltv_url', models.URLField(blank=True, help_text='HLTV tournament page URL (e.g., https://www.hltv.org/events/7148/...)', null=True)),
                ('order', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('next_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_stages', to='fantasy.stage')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='fantasy.tournament')),
            ],
            options={
                'ordering': ['tournament', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='basemodule',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modules', to='fantasy.stage'),
        ),
        migrations.CreateModel(
            name='StatPredictionDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source_url', models.URLField(blank=True, help_text='HLTV stats page URL. Auto-populated from category template if empty.', null=True)),
                ('invert_results', models.BooleanField(default=False, help_text="If true, result list from HLTV should be inverted (reversed). Useful for stats where lower is better (e.g., 'Deaths per round').")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fantasy.statpredictioncategory')),
                ('options', models.ManyToManyField(to='fantasy.predictionoption')),
                ('scoring_rule', models.ForeignKey(blank=True, help_text='Optional definition-level scoring rule (overrides module-level scoring if set)', null=True, on_delete=django.db.models.deletion.PROTECT, to='fantasy.statpredictionscoringrule')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='fantasy.statpredictionsmodule')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='StatPredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('results', models.JSONField(help_text='The actual results, e.g., a leaderboard of players.')),
                ('is_final', models.BooleanField(default=False, help_text='Indicates if the results are final and scored.')),
                ('definition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='fantasy.statpredictiondefinition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='statpredictioncategory',
            name='default_scoring_rule',
            field=models.ForeignKey(blank=True, help_text='Optional default scoring rule for this category (can be overridden per definition)', null=True, on_delete=django.db.models.deletion.PROTECT, to='fantasy.statpredictionscoringrule'),
        ),
        migrations.CreateModel(
            name='SwissModuleScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_per_user', models.IntegerField(default=3)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fantasy.swissscore')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='fantasy.swissmodule')),
            ],
        ),
        migrations.AddField(
            model_name='swissscore',
            name='groups',
            field=models.ManyToManyField(to='fantasy.swissscoregroup'),
        ),
        migrations.AddField(
            model_name='basemodule',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='fantasy.tournament'),
        ),
        migrations.CreateModel(
            name='UserModuleScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points', models.IntegerField(default=0)),
                ('score_breakdown', models.JSONField(blank=True, default=list, help_text='Detailed breakdown of how points were scored.')),
                ('is_final', models.BooleanField(default=False)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserBracketPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.bracket')),
            ],
            options={
                'unique_together': {('user', 'bracket')},
            },
        ),
        migrations.AddField(
            model_name='swissmodule',
            name='teams',
            field=models.ManyToManyField(related_name='swiss_modules', to='fantasy.team'),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('predictionoption_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fantasy.predictionoption')),
                ('hltv_id', models.IntegerField(blank=True, help_text="The player's ID on HLTV.org", null=True, unique=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('hltv_stats_page', models.URLField(blank=True, null=True)),
                ('aliases', models.JSONField(blank=True, default=list, help_text="List of alternative names for search purposes (e.g., 'simple' for 's1mple').")),
                ('active_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='fantasy.team')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=('fantasy.predictionoption',),
        ),
        migrations.CreateModel(
            name='BracketMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('round', models.IntegerField()),
                ('best_of', models.IntegerField(default=3)),
                ('hltv_match_id', models.IntegerField(blank=True, help_text='Match ID from HLTV.org', null=True, unique=True)),
                ('team_a_score', models.IntegerField(blank=True, null=True)),
                ('team_b_score', models.IntegerField(blank=True, null=True)),
                ('loser_to_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeder_for_loser', to='fantasy.bracketmatch')),
                ('winner_to_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeder_for_winner', to='fantasy.bracketmatch')),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='fantasy.bracket')),
                ('team_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bracket_matches_a', to='fantasy.team')),
                ('team_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bracket_matches_b', to='fantasy.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bracket_wins', to='fantasy.team')),
            ],
            options={
                'verbose_name_plural': 'Bracket matches',
                'ordering': ['round', 'created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='swissscore',
            unique_together={('wins', 'losses')},
        ),
        migrations.CreateModel(
            name='UserBracketModuleScore',
            fields=[
                ('usermodulescore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fantasy.usermodulescore')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.bracket')),
            ],
            options={
                'abstract': False,
            },
            bases=('fantasy.usermodulescore',),
        ),
        migrations.CreateModel(
            name='UserStatPredictionsModuleScore',
            fields=[
                ('usermodulescore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fantasy.usermodulescore')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.statpredictionsmodule')),
            ],
            options={
                'abstract': False,
            },
            bases=('fantasy.usermodulescore',),
        ),
        migrations.CreateModel(
            name='UserSwissModuleScore',
            fields=[
                ('usermodulescore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fantasy.usermodulescore')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.swissmodule')),
            ],
            options={
                'abstract': False,
            },
            bases=('fantasy.usermodulescore',),
        ),
        migrations.CreateModel(
            name='UserTournamentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_points', models.IntegerField(default=0)),
                ('is_final', models.BooleanField(default=False)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'tournament')},
            },
        ),
        migrations.CreateModel(
            name='UserMatchPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('predicted_team_a_score', models.IntegerField(blank=True, null=True)),
                ('predicted_team_b_score', models.IntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.bracketmatch')),
                ('user_bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_predictions', to='fantasy.userbracketprediction')),
                ('predicted_winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.team')),
                ('team_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fantasy.team')),
                ('team_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fantasy.team')),
            ],
            options={
                'unique_together': {('user_bracket', 'match')},
            },
        ),
        migrations.CreateModel(
            name='SwissResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='fantasy.swissmodulescore')),
                ('swiss_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='fantasy.swissmodule')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.team')),
            ],
            options={
                'ordering': ['swiss_module', 'team'],
                'unique_together': {('swiss_module', 'team')},
            },
        ),
        migrations.CreateModel(
            name='SwissPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0)),
                ('predicted_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='fantasy.swissmodulescore')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('swiss_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='fantasy.swissmodule')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.team')),
            ],
            options={
                'ordering': ['swiss_module', 'user', 'team'],
                'unique_together': {('user', 'swiss_module', 'team')},
            },
        ),
        migrations.CreateModel(
            name='StatPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('predicted_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='fantasy.statpredictiondefinition')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fantasy.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fantasy.team')),
            ],
            options={
                'unique_together': {('user', 'definition')},
            },
        ),
    ]
