# Generated by Django 5.2.7 on 2025-11-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statpredictionscoringrule',
            old_name='rules',
            new_name='scoring_config',
        ),
        migrations.AddField(
            model_name='basemodule',
            name='max_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basemodule',
            name='min_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statpredictionscoringrule',
            name='max_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statpredictionscoringrule',
            name='min_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
