# Generated by Django 5.2.7 on 2025-11-25 20:49

from django.db import migrations, models
import re


def extract_event_ids_and_update_definitions(apps, schema_editor):
    """
    Extract event IDs from stage and tournament URLs, then regenerate all
    StatPredictionDefinition source URLs with correct event IDs.
    """
    Stage = apps.get_model("fantasy", "Stage")
    Tournament = apps.get_model("fantasy", "Tournament")
    StatPredictionDefinition = apps.get_model("fantasy", "StatPredictionDefinition")

    for stage in Stage.objects.all():
        if stage.hltv_url:
            match = re.search(r"/events/(\d+)/", stage.hltv_url)
            if match:
                stage.hltv_event_id = int(match.group(1))
                stage.save(update_fields=["hltv_event_id"])

    for tournament in Tournament.objects.all():
        if tournament.hltv_url and not tournament.hltv_event_id:
            match = re.search(r"/events/(\d+)/", tournament.hltv_url)
            if match:
                tournament.hltv_event_id = int(match.group(1))
                tournament.save(update_fields=["hltv_event_id"])

    definitions_updated = 0
    for definition in StatPredictionDefinition.objects.select_related(
        "module__stage", "module__tournament", "category"
    ).all():
        category = definition.category

        if not category.url_template:
            continue

        event_id = None
        if definition.module.stage and definition.module.stage.hltv_event_id:
            event_id = definition.module.stage.hltv_event_id
        elif definition.module.tournament.hltv_event_id:
            event_id = definition.module.tournament.hltv_event_id

        if event_id:
            new_url = category.url_template.format(event_id=event_id)
            if definition.source_url != new_url:
                definition.source_url = new_url
                definition.save(update_fields=["source_url"])
                definitions_updated += 1

    print(
        f"Migration complete: Updated {definitions_updated} StatPredictionDefinition URLs"
    )


def reverse_migration(apps, schema_editor):
    """Nothing to reverse - URLs can remain as-is."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("fantasy", "0002_add_max_min_score_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="stage",
            name="hltv_event_id",
            field=models.IntegerField(
                blank=True,
                help_text="HLTV event ID extracted from hltv_url (for URL template substitution)",
                null=True,
            ),
        ),
        migrations.RunPython(
            extract_event_ids_and_update_definitions, reverse_migration
        ),
    ]
