# Generated by Django 5.2.7 on 2025-12-04 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_notification_channels(apps, schema_editor):
    NotificationChannel = apps.get_model("fantasy", "NotificationChannel")

    channels = [
        {
            "name": "Mobile",
            "tag": "mobile",
            "description": "Push notifications to mobile devices",
            "is_admin_only": False,
            "default_enabled": True,
            "order": 0,
        },
        {
            "name": "Discord",
            "tag": "discord",
            "description": "Notifications via Discord",
            "is_admin_only": False,
            "default_enabled": True,
            "order": 1,
        },
        {
            "name": "Admin",
            "tag": "admin",
            "description": "Admin-only notification channel",
            "is_admin_only": True,
            "default_enabled": True,
            "order": 2,
        },
    ]

    for channel_data in channels:
        NotificationChannel.objects.get_or_create(
            tag=channel_data["tag"], defaults=channel_data
        )


def seed_notification_types(apps, schema_editor):
    NotificationType = apps.get_model("fantasy", "NotificationType")

    notification_types = [
        {
            "name": "Admin Error",
            "tag": "admin_error",
            "description": "Critical errors and task failures requiring admin attention",
            "is_admin_only": True,
            "default_enabled": True,
        },
        {
            "name": "Deadline Reminder",
            "tag": "deadline_reminder",
            "description": "Prediction deadline approaching",
            "is_admin_only": False,
            "default_enabled": True,
        },
        {
            "name": "Module Complete",
            "tag": "module_complete",
            "description": "Module has been finalized with results",
            "is_admin_only": False,
            "default_enabled": True,
        },
        {
            "name": "Score Update",
            "tag": "score_update",
            "description": "Scores have been calculated",
            "is_admin_only": False,
            "default_enabled": False,
        },
        {
            "name": "Stage Advancement",
            "tag": "stage_advancement",
            "description": "Stage completed and next stage activated",
            "is_admin_only": True,
            "default_enabled": True,
        },
        {
            "name": "Population Retry",
            "tag": "population_retry",
            "description": "Module population retry scheduled",
            "is_admin_only": True,
            "default_enabled": False,
        },
        {
            "name": "Population Failed",
            "tag": "population_failed",
            "description": "Module population max retries exceeded",
            "is_admin_only": True,
            "default_enabled": True,
        },
    ]

    for nt_data in notification_types:
        NotificationType.objects.get_or_create(tag=nt_data["tag"], defaults=nt_data)


def create_notification_settings_for_existing_users(apps, schema_editor):
    User = apps.get_model("fantasy", "User")
    UserNotificationSettings = apps.get_model("fantasy", "UserNotificationSettings")
    NotificationType = apps.get_model("fantasy", "NotificationType")
    NotificationChannel = apps.get_model("fantasy", "NotificationChannel")
    UserNotificationPreference = apps.get_model("fantasy", "UserNotificationPreference")

    for user in User.objects.all():
        notifications_enabled = user.is_superuser
        settings, created = UserNotificationSettings.objects.get_or_create(
            user=user, defaults={"notifications_enabled": notifications_enabled}
        )

        # Create preferences for existing users
        if user.is_superuser:
            notification_types = NotificationType.objects.filter(
                is_active=True, default_enabled=True
            )
            channels = NotificationChannel.objects.filter(
                is_active=True, default_enabled=True
            )
        else:
            notification_types = NotificationType.objects.filter(
                is_active=True, is_admin_only=False, default_enabled=True
            )
            channels = NotificationChannel.objects.filter(
                is_active=True, is_admin_only=False, default_enabled=True
            )

        for notif_type in notification_types:
            for channel in channels:
                UserNotificationPreference.objects.get_or_create(
                    user=user,
                    notification_type=notif_type,
                    channel=channel,
                    defaults={"enabled": True}
                )


class Migration(migrations.Migration):
    dependencies = [
        ("fantasy", "0003_add_stage_hltv_event_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "tag",
                    models.SlugField(
                        help_text="Tag used in Apprise API (e.g., 'mobile', 'discord')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_admin_only",
                    models.BooleanField(
                        default=False, help_text="Only visible to admin/superuser users"
                    ),
                ),
                (
                    "default_enabled",
                    models.BooleanField(
                        default=True, help_text="Enabled by default for new users"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Display order in UI"),
                ),
            ],
            options={
                "db_table": "notification_channels",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="NotificationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("tag", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_admin_only", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "default_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this notification is enabled by default for new users",
                    ),
                ),
            ],
            options={
                "db_table": "notification_types",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="uses_password",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="UserNotificationSettings",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="notification_settings",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notifications_enabled",
                    models.BooleanField(
                        default=True, help_text="Master switch for all notifications"
                    ),
                ),
                (
                    "enabled_types",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Notification types this user wants to receive (DEPRECATED: use UserNotificationPreference)",
                        related_name="user_settings",
                        to="fantasy.notificationtype",
                    ),
                ),
            ],
            options={
                "db_table": "user_notification_settings",
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("user", "User"),
                            ("all_users", "All Users"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                (
                    "config_count",
                    models.IntegerField(
                        default=0, help_text="Number of Apprise configs attempted"
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notification_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="fantasy.notificationtype",
                    ),
                ),
            ],
            options={
                "db_table": "notification_logs",
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["-sent_at"], name="notificatio_sent_at_8136c8_idx"
                    ),
                    models.Index(
                        fields=["notification_type", "-sent_at"],
                        name="notificatio_notific_eec4c3_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserNotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_preferences",
                        to="fantasy.notificationchannel",
                    ),
                ),
                (
                    "notification_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_preferences",
                        to="fantasy.notificationtype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_notification_preferences",
                "indexes": [
                    models.Index(
                        fields=["user", "notification_type"],
                        name="user_notifi_user_id_d3244e_idx",
                    ),
                    models.Index(
                        fields=["user", "enabled"],
                        name="user_notifi_user_id_fd5251_idx",
                    ),
                ],
                "unique_together": {("user", "notification_type", "channel")},
            },
        ),
        migrations.RunPython(seed_notification_channels, migrations.RunPython.noop),
        migrations.RunPython(seed_notification_types, migrations.RunPython.noop),
        migrations.RunPython(
            create_notification_settings_for_existing_users, migrations.RunPython.noop
        ),
    ]
