# Generated by Django 5.2.7 on 2025-12-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0003_add_stage_hltv_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uses_password',
            field=models.BooleanField(default=False),
        ),
    ]
