# Generated by Django 5.2.7 on 2025-12-08 10:39

from django.db import migrations, models


def update_bracket_scoring_configs(apps, schema_editor):
    """
    Update all existing Bracket modules to use the new default scoring config.
    """
    Bracket = apps.get_model("fantasy", "Bracket")
    from fantasy.models.bracket import get_default_bracket_scoring_config

    new_config = get_default_bracket_scoring_config()
    for bracket in Bracket.objects.all():
        bracket.scoring_config = new_config
        bracket.save(update_fields=["scoring_config"])


def auto_tag_existing_matches(apps, schema_editor):
    """
    Auto-tag existing bracket matches based on their round number.
    """
    Bracket = apps.get_model("fantasy", "Bracket")
    for bracket in Bracket.objects.all():
        all_matches = list(bracket.matches.all())
        if not all_matches:
            continue

        max_round = max(m.round for m in all_matches)

        for match in all_matches:
            tags = []
            if match.round == max_round:
                tags.append("final")
            elif match.round == max_round - 1:
                tags.append("semi-final")
            elif match.round == max_round - 2:
                tags.append("quarter-final")

            if tags:
                match.tags = tags
                match.save(update_fields=["tags"])


def forwards_func(apps, schema_editor):
    """Combines all data migration functions."""
    update_bracket_scoring_configs(apps, schema_editor)
    auto_tag_existing_matches(apps, schema_editor)


class Migration(migrations.Migration):
    dependencies = [
        ("fantasy", "0004_notificationchannel_notificationtype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bracketmatch",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Tags for special scoring rules, e.g., ['final', 'semi-final']",
            ),
        ),
        migrations.AlterField(
            model_name="statpredictiondefinition",
            name="options",
            field=models.ManyToManyField(blank=True, to="fantasy.predictionoption"),
        ),
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop),
    ]
